apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: php-apache
      name: php-apache
    spec:
      containers:
      - name: php-apache
        image: viejo/php-apache:health-check
        tty: true
        resources:
          requests:
            memory: "32M"
            cpu: "20m"
          limits:
            memory: "64M"
            cpu: "40m"
        livenessProbe:
          httpGet:
            path: /healthz/
            port: 80
            httpHeaders:
            - name: X-Custom-Header
              value: Ackstorm
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10