apiVersion: v1
kind: Pod
metadata:
  name: lab2-pod
  labels:
    labs: lab2
spec:
  containers:
  - name: busybox
    image: busybox
    tty: true
    command: ["/bin/sh", "-c"]
    args: ["wget -O /tmp/landing/image.jpg https://bit.ly/3724M8P; sleep 100000"]
    volumeMounts:
    - name: shared-vol
      mountPath: "/tmp/landing"
  - name: nginx
    image: viejo/nginx-debian
    ports:
    - containerPort: 80
    command: ["nginx", "-g", "daemon off;"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: shared-vol
      mountPath: "/var/www/html/"
    - name: nginx-log
      mountPath: "/var/log/nginx"
  volumes:
  - name: nginx-log
    hostPath:
      path: /var/training
  - name: shared-vol
    emptyDir: {}