apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3-deploy
  labels:
    labs: lab3
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2   # kubectl set image deploy lab3-deploy nginx=nginx
        ports:
        - containerPort: 80
        
